name: Deploy Seguro Vercel
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o Código
        uses: actions/checkout@v3

      - name: Injetando as Chaves Secretas
        run: |
          sed -i "s|V_URL|${{ secrets.SUPABASE_URL }}|g" index.html
          sed -i "s|V_KEY|${{ secrets.SUPABASE_ANON_KEY }}|g" index.html

      - name: Enviando para a Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'